services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: filebeat
    user: root
    command: -e --strict.perms=false
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/var/log
    networks:
      - elastic
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  filebeat: {}

networks:
  elastic:
    external: true
    name: elastic
  
configs:
  fb_config:
    name: fb_config
    file: ./filebeat.yml