services:
  domain_exporter:
    image: caarlos0/domain_exporter:v1.23.0
    restart: always
    container_name: domain_exporter
    ports:
      - 9222:9222
    networks:
      - prome_network

networks:
  prome_network:
    external: true
    name: prome_network
