version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.45.0
    user: "1003"
    restart: always
    command: --storage.tsdb.retention.time=10d --storage.tsdb.retention.size=50GB --web.enable-remote-write-receiver --web.enable-admin-api --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --web.config.file=/etc/prometheus/web.yml
    volumes:
      - "./conf:/etc/prometheus/"
      - "./data/prometheus:/prometheus"
    ports:
      - "9090:9090"
