services:
  auditbeat:
    image: docker.elastic.co/beats/auditbeat:8.15.0
    container_name: auditbeat
    command: -e --strict.perms=false # -e flag to log to stderr and disable syslog/file output
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    configs:
      - source: ab_config
        target: /usr/share/auditbeat/auditbeat.yml
    # Auditbeat must run in the main process namespace.
    pid: host
    networks:
      - elastic
    healthcheck:
      test: auditbeat --strict.perms=false test config
      interval: 30s
      timeout: 15s
      retries: 5

networks:
  elastic:
    external: true
    name: elastic
  
configs:
  ab_config:
    name: ab_config
    file: ./auditbeat.yml