services:
  jms:
    image: jumpserver/jms_all:${VERSION}
    container_name: jms
    restart: unless-stopped
    env_file: .env
    user: root
    privileged: true
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
      - ${VOLUME_DIR}/web/log:/var/log/nginx
    ports:
      - 2222:2222
    networks:
      - net
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0.39-debian
    container_name: jms_mysql
    restart: unless-stopped
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ${VOLUME_DIR}/mysql/data:/var/lib/mysql
    networks:
      - net

  redis:
    image: redis:7.4.0
    container_name: jms_redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass $REDIS_PASSWORD 
    environment:
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p $$REDIS_PORT -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${VOLUME_DIR}/redis/data:/data
    networks:
      - net

networks:
  net:
    external: true
    name: net