# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    basic_auth:
        username: admin
        password: 7iDk5jbAe5JH
    static_configs:
    - targets: ['127.0.0.1:9090']


  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics?format=prometheus_all_hosts&source=raw'
    relabel_configs:
    - source_labels: [exported_instance]
      target_label: instance
      action: replace
    static_configs:
    - targets: ['DB-01:19999']    
     
  - job_name: 'netdata_scrape'
    metrics_path: '/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP
      format: [prometheus_all_hosts]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      #source: [as-collected]
      #
      # server name for this prometheus - the default is the client IP
      # for Netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true
    relabel_configs:
      - source_labels:  ["__address__"]
        target_label: "endpoint"
    metric_relabel_configs:
      - action: labelmap
        regex: (family)
        replacement: tmp_$1
      - action: labeldrop
        regex: (^family$)
      - action: labelmap
        regex: tmp_(family)
        replacement: $1
      - action: labeldrop
        regex: (^tmp_family$)
    static_configs:
      - targets: ['WEB-01:19999'] 

