services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./v1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./v1/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80