services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    command: sleep 3600
    env_file:
      - ./nacos.env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0.39
    env_file:
      - ./mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
    name: mysql_data
    external: true