services:
  jenkins:
    build: .
    container_name: jenkins
    volumes:
      - /opt/jenkins/data:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - net
    expose:
      - "8080"
    ports:
      - 50000:50000
    restart: unless-stopped

networks:
  net:
    external: true
    name: net    