version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    networks:
      - elastic
    volumes:
      - data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  data:
  certs: