version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    networks:
      - elastic
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  kibana:
    container_name: kibana
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge