services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LANG: C.UTF-8
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    configs:
      - source: mysql_config
        target: /etc/mysql/my.cnf
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

volumes:
  mysql_data:
    name: dev_mysql_data
    external: true
  


configs:
  mysql_config:
    file: ./configs/my.cnf