version: '3'

services:
  db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./mysql-1/conf:/etc/mysql/conf.d
      - ./mysql-1/data:/var/lib/mysql
      - ./mysql-1/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - 3306:3306
  # db-2:
  #   image: mysql:8.0.32
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes: 
  #     - ./mysql-2/conf:/etc/mysql/conf.d
  #     - ./mysql-2/data:/var/lib/mysql
  #     - ./mysql-2/log:/var/log/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test1234
  #   ports:
  #     - 3307:3306